import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mock Interview App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
             <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        {children}</body>
    </html>
    </ClerkProvider>
   
  );
}
